language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: 
  - npm test
  - npm run coverage
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-west-1"
  app: "smarttodo-express"
  env: "SmarttodoExpress-env"
  bucket_name: $BUCKETNAME
  on:
    branch: master